import os
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill

# 1. Define the generic architecture
BASE_DIR = "apex_retail"
BRANCHES = ["north", "south", "east"]
TARGET_FILE = "Apex_Master_Ledger.xlsx"

def create_messy_export(filepath, title, data_df):
    """Simulates a regional POS export designed for human eyes, not machines."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Export"

    # Add a messy, merged corporate title banner
    ws.merge_cells('A1:F2')
    title_cell = ws['A1']
    title_cell.value = f"APEX RETAIL CO. - {title.upper()}"
    title_cell.font = Font(size=16, bold=True, color="FFFFFF")
    title_cell.fill = PatternFill(start_color="1A365D", fill_type="solid")
    title_cell.alignment = Alignment(horizontal="center", vertical="center")

    # Add some spacer rows (simulating bad export formatting)
    ws['A3'] = "Generated By: System Admin"
    ws['A4'] = "Confidential Internal Report"

    # Drop the actual data table starting on Row 6 (Index 5)
    # Write Headers
    for col_idx, column in enumerate(data_df.columns, start=1):
        ws.cell(row=6, column=col_idx, value=column).font = Font(bold=True)

    # Write Data
    for row_idx, row in enumerate(data_df.values, start=7):
        for col_idx, value in enumerate(row, start=1):
            ws.cell(row=row_idx, column=col_idx, value=value)

    wb.save(filepath)

def setup_environment():
    print("🚀 Initializing Apex Retail Mock Environment...")

    # 2. Build Directory Tree
    for branch in BRANCHES:
        os.makedirs(os.path.join(BASE_DIR, branch, "sending"), exist_ok=True)
        os.makedirs(os.path.join(BASE_DIR, branch, "receiving"), exist_ok=True)

    # 3. Generate Fake 'Messy' Sending Data
    # North sends to South and East
    north_send = pd.DataFrame({
        "Date": ["2026-07-01", "2026-07-02"],
        "Receipt #": ["REC-1001", "REC-1002"],
        "Receipt Type": ["Sales", "Sales"],
        "Total": [4500, 8200],
        "Full Name": ["South Branch Store", "East Branch Store"]
    })
    create_messy_export(f"{BASE_DIR}/north/sending/north_outbound.xlsx", "North Outbound", north_send)

    # 4. Generate Fake 'Messy' Receiving Data (Matching the sending data)
    # South receives from North
    south_recv = pd.DataFrame({
        "Date": ["2026-07-03"],
        "Voucher #": ["VOUCH-881"],
        "Type": ["Receiving"],
        "Invoice #": ["REC-1001"], # Matches North's send
        "Vendor": ["North Branch"],
        "Total": [4500]
    })
    create_messy_export(f"{BASE_DIR}/south/receiving/south_inbound.xlsx", "South Inbound", south_recv)

    # East receives from North
    east_recv = pd.DataFrame({
        "Date": ["2026-07-04"],
        "Voucher #": ["VOUCH-905"],
        "Type": ["Receiving"],
        "Invoice #": ["REC-1002"], # Matches North's send
        "Vendor": ["North Branch"],
        "Total": [8200]
    })
    create_messy_export(f"{BASE_DIR}/east/receiving/east_inbound.xlsx", "East Inbound", east_recv)

    # 5. Generate Empty Master Ledger Target
    wb = Workbook()
    wb.remove(wb.active) # Remove default sheet
    for branch in BRANCHES:
        ws = wb.create_sheet(f"{branch.capitalize()} Store")
        # Layout matching your production structure
        ws.append(["Apex Unified Corporate Ledger"])
        ws.append(["Sending Info", "", "", "", "", "Receiving Info"])
        ws.append(["From", "SentOn", "Sending#", "OperationType", "AmountSent", "To", "ReceivedOn", "StockTransfer#", "Receiving #", "OperationType.1", "AmountReceived"])
    wb.save(TARGET_FILE)

    print(f"✅ Environment created! Target ledger '{TARGET_FILE}' and '{BASE_DIR}/' directories are ready for the demo.")

if __name__ == "__main__":
    setup_environment()
